#pragma once

#define VER_PRODUCTBUILD 560
#define VER_PRODUCTVERSION_STR_W L"846b73f"
#define VER_FILEVERSION_STR_W VER_PRODUCTVERSION_STR_W
#define VER_BRANCHVERSION_STR_W L"piebotc/LegacyEvolved/main"
#define VER_NETWORK VER_PRODUCTBUILD
